basePath: /api/v1
definitions:
  dto.Category:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  dto.CategoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  dto.Response:
    properties:
      description:
        type: string
      errorCode:
        type: string
      meta:
        type: object
      payload:
        type: object
    type: object
info:
  contact: {}
  description: API for processing clients data
  title: Coffe-Life API
  version: "1.0"
paths:
  /admin/categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: categories
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/dto.Category'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create category
      parameters:
      - description: Category
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: category
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                payload:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create category
      tags:
      - categories
  /admin/categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete category
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: category
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                payload:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Delete category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update category
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: Category
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: category
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                payload:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Update category
      tags:
      - categories
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
