basePath: /api/v1
info:
  contact: {}
  description: API for processing clients data
  title: Coffe-Life API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
